// This file was generated by counterfeiter
package fake

import (
	"sync"

	"github.com/phogolabs/parcel"
)

type Compressor struct {
	CompressStub        func(fileSystem parcel.FileSystem) (*parcel.Bundle, error)
	compressMutex       sync.RWMutex
	compressArgsForCall []struct {
		fileSystem parcel.FileSystem
	}
	compressReturns struct {
		result1 *parcel.Bundle
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Compressor) Compress(fileSystem parcel.FileSystem) (*parcel.Bundle, error) {
	fake.compressMutex.Lock()
	fake.compressArgsForCall = append(fake.compressArgsForCall, struct {
		fileSystem parcel.FileSystem
	}{fileSystem})
	fake.recordInvocation("Compress", []interface{}{fileSystem})
	fake.compressMutex.Unlock()
	if fake.CompressStub != nil {
		return fake.CompressStub(fileSystem)
	}
	return fake.compressReturns.result1, fake.compressReturns.result2
}

func (fake *Compressor) CompressCallCount() int {
	fake.compressMutex.RLock()
	defer fake.compressMutex.RUnlock()
	return len(fake.compressArgsForCall)
}

func (fake *Compressor) CompressArgsForCall(i int) parcel.FileSystem {
	fake.compressMutex.RLock()
	defer fake.compressMutex.RUnlock()
	return fake.compressArgsForCall[i].fileSystem
}

func (fake *Compressor) CompressReturns(result1 *parcel.Bundle, result2 error) {
	fake.CompressStub = nil
	fake.compressReturns = struct {
		result1 *parcel.Bundle
		result2 error
	}{result1, result2}
}

func (fake *Compressor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.compressMutex.RLock()
	defer fake.compressMutex.RUnlock()
	return fake.invocations
}

func (fake *Compressor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ parcel.Compressor = new(Compressor)
